name: Build & Publish rust emscripten-wasm-eh sysroot
on:
  workflow_dispatch:
    inputs:
      emcc_version:
        description: Version of emcc to use
        required: true
      rust_nightly_date:
        description: Rust nightly date
        required: true

jobs:
  pyodide-packages:
    name: Build & Publish rust emscripten-wasm-eh sysroot
    runs-on: ubuntu-latest
    steps:
      - name: Free unused disk space
        run: |
          # delete packages
          sudo apt-get remove -y '^dotnet-.*' || true
          sudo apt-get remove -y '^llvm-.*' || true
          sudo apt-get remove -y '^temurin-.*' || true
          sudo apt-get remove -y '^mysql-server-core-.*' || true
          sudo apt-get remove -y '^postgresql-.*' || true
          sudo apt-get remove -y azure-cli google-chrome-stable google-cloud-cli firefox powershell microsoft-edge-stable mono-devel || true
          sudo apt-get autoremove -y
          sudo apt-get clean

          # delete directories
          sudo rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/share/swift/
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/android

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.8

      - name: Build Rust sysroot
        run: |
          ./main.sh ${{ inputs.emcc_version }} ${{ inputs.rust_nightly_date }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "emcc-{{ inputs.emcc_version }}_nightly-{{ inputs.rust_nightly_date }}.tar.bz2"
          tag: emcc-{{ inputs.emcc_version }}_nightly-{{ inputs.rust_nightly_date }}
          draft: false
          prerelease: false
